### ISSUE TITLE
Add a solution of 2022 Round b

### ISSUE THREAD

**Issue by saty-a** [saty-a/Google-Kick-Start#13]

**Comment by itsNisarg** [comment]
@saty-a.
I would like to do this one. Thanks.

**Comment by OneAutumLeaf** [comment]
Hi, @saty-a.
I would like to do the Infinity Area Problem from Kickstart 2022 Round B . Could you please assign this to me?

**Comment by saty-a** [comment]
> Hi, @saty-a. I would like to do the Infinity Area Problem from Kickstart 2022 Round B . Could you please assign this to me?

Sure @OneAutumLeaf

**Comment by Thunder429** [comment]
I would like to solve Palindromic Factors problem, Please assign me

**Comment by saty-a** [comment]
> I would like to solve Palindromic Factors problem, Please assign me

sure!
