### ISSUE TITLE
Add a solution of 2022 Round c

### ISSUE THREAD

**Issue by saty-a** [saty-a/Google-Kick-Start#14]

**Comment by hardikhans01** [comment]
Hi, @saty-a.
I would like to do the Range Partition Problem from Kickstart 2022 Round C . Could you please assign this to me?

**Comment by saty-a** [comment]
> Hi, @saty-a. I would like to do the Range Partition Problem from Kickstart 2022 Round C . Could you please assign this to me?

sure!

**Comment by hardikhans01** [comment]
Yes Sir

**Comment by Thunder429** [comment]
I would like to solve the problem New Password of round C

**Comment by saty-a** [comment]
> I would like to solve the problem New Password of round C

sure!

**Comment by hardikhans01** [comment]
Sorry Sir , 
By mistake , I have submitted New Password instead of Range Partition Problem .
I am also having the solution of Range Partition Problem.
Could you please re-assign the task .

**Comment by saty-a** [comment]
> Sorry Sir , By mistake , I have submitted New Password instead of Range Partition Problem . I am also having the solution of Range Partition Problem. Could you please re-assign the task .

I've already assigned you! just make the pull request for the latest changes.

**Comment by hardikhans01** [comment]
#42 
Sir I have made the pull request.
