### ISSUE TITLE
Add a solution of 2020 Round a

### ISSUE THREAD

**Issue by saty-a** [saty-a/Google-Kick-Start#15]

**Comment by itsNisarg** [comment]
Hi, @saty-a.
I would like to do the Allocation problem from Kickstart 2020 Round A. Could you please assign this to me?

**Comment by Thunder429** [comment]
Hi @saty-a , I'd like to work on problem New Password. Please assign it to me.

**Comment by Thunder429** [comment]
New password is problem of google kickstart 2022. Sorry, I am doing the Problem bundling of round A google kickstart 2020

**Comment by saty-a** [comment]
> New password is problem of google kickstart 2022. Sorry, I am doing the Problem bundling of round A google kickstart 2020

no worries but when you pull request then just place in the correct order with the respective directories..
