### ISSUE TITLE
Contribute any one problem with any programming language in this repo

### ISSUE THREAD

**Issue by saty-a** [saty-a/Google-Kick-Start#18]

**Comment by Esha-in-arena** [comment]
Hey @saty-a I want to contribute .kindly assign this to me

**Comment by RKSingh5** [comment]
please assign this issue to me

**Comment by theadityaagnihotri** [comment]
can i work on it?

**Comment by saty-a** [comment]
> can i work on it?

okay!

**Comment by RKSingh5** [comment]
Added infix to postfix expression change using stack in C  #35
