### ISSUE TITLE
Add hyperlinks in readme file for each questions and respective answers

### ISSUE THREAD

**Issue by saty-a** [saty-a/Google-Kick-Start#29]
Add hyperlinks in readme file for each questions and respective answers

**Comment by Chaitanya-087** [comment]
i would like to work on this issue

**Comment by saty-a** [comment]
> i would like to work on this issue

Sure!!

**Comment by Harikrishna3** [comment]
Hello, @0shivamh. I'd like to work on this; could you please assign it to me?

**Comment by Harikrishna3** [comment]
Hello, @saty-a . I'd like to work on this; could you please assign it to me?

**Comment by saty-a** [comment]
> Hello, @saty-a . I'd like to work on this; could you please assign it to me?

Okay

**Comment by Harikrishna3** [comment]
Can you please tell me how to proceed?
