### ISSUE TITLE
Add solutions with python or any other language for any problem 

### ISSUE THREAD

**Issue by saty-a** [saty-a/Google-Kick-Start#30]
Add solutions with python or any other language for any problem in there respective directory

**Comment by theadityaagnihotri** [comment]
can i work on this?

**Comment by saty-a** [comment]
> can i work on this?

Sure!

**Comment by aditya-agr** [comment]
I can work on it effectively and I can solve any problem with very optimistic solution.

**Comment by saty-a** [comment]
> I can work on it effectively and I can solve any problem with very optimistic solution.

sure!!

**Comment by Thunder429** [comment]
I would like to add solution in c++ or python. Please assign me any issue.

**Comment by amanpandey2101** [comment]
can you please assign me for this issue?
