### ISSUE TITLE
Submit solution for Google Kick Start 2019 Round H H-Index

### ISSUE THREAD

**Issue by saty-a** [saty-a/Google-Kick-Start#7]
Submit solution for Google Kick Start 2019 Round H H-Index Question in any programming language. The question is mentioned in the respective directory.

**Comment by kiranmayek** [comment]
Please assign me this and if possible please add hacktober label to this

**Comment by kiranmayek** [comment]
could you please add hacktober label @saty-a

**Comment by saty-a** [comment]
> could you please add hacktober label @saty-a

sure!
